/* Los textos de la adquisición asistida */
var SF_TEXTOS = window.SF_TEXTOS = {
 "_doctrina": "Los textos de la adquisición asistida.",
 "textos": {
  "es": {
   "tit_doc": "📄 El documento",
   "tit_llevar": "📋 Llevarlo a claude.ai",
   "tit_traer": "📥 Traer la respuesta",
   "tit_diario": "📓 El diario",
   "doc_suelte": "Suelte aquí un PDF, o toque para elegirlo",
   "doc_o_pegue": "…o pegue el texto directamente, si ya lo tiene",
   "doc_pegar": "Pegar el texto aquí",
   "doc_ocr": "🔍 Reconocer el texto (OCR)",
   "doc_ocr_curso": "⏳ Reconociendo…",
   "doc_ocr_hecho": "✓ Texto reconocido",
   "doc_sin_servidor": "El OCR necesita el servidor. Arranque Salufolio con su abeja 🐝 —o escriba <code>salufolio</code>— y vuelva aquí.",
   "lle_expl": "Copie todo —la pregunta y el texto— y péguelo en una conversación de claude.ai. Después traiga la respuesta aquí.",
   "lle_copiar": "📋 Copiar la pregunta y el texto",
   "lle_copiado": "✓ Copiado — péguelo en claude.ai",
   "lle_abrir": "↗ Abrir claude.ai",
   "tra_expl": "Pegue aquí lo que claude.ai ha devuelto. Es un objeto JSON: empieza por { y termina por }.",
   "tra_pegar": "Pegue aquí la respuesta",
   "tra_guardar": "✓ Guardar en el expediente",
   "tra_leido": "Leído",
   "tra_mal": "Eso no parece un JSON. Copie la respuesta entera, sin el texto de alrededor.",
   "dia_vacio": "El diario está vacío.",
   "sin_exp": "⚠ ningún expediente abierto"
  },
  "fr": {
   "tit_doc": "📄 Le document",
   "tit_llevar": "📋 Le porter à claude.ai",
   "tit_traer": "📥 Rapporter la réponse",
   "tit_diario": "📓 Le journal",
   "doc_suelte": "Déposez un PDF ici, ou touchez pour le choisir",
   "doc_o_pegue": "…ou collez le texte directement, si vous l'avez déjà",
   "doc_pegar": "Collez le texte ici",
   "doc_ocr": "🔍 Reconnaître le texte (OCR)",
   "doc_ocr_curso": "⏳ Reconnaissance…",
   "doc_ocr_hecho": "✓ Texte reconnu",
   "doc_sin_servidor": "L'OCR a besoin du serveur. Lancez Salufolio par son abeille 🐝 —ou tapez <code>salufolio</code>— et revenez ici.",
   "lle_expl": "Copiez tout —la question et le texte— et collez-le dans une conversation claude.ai. Puis rapportez la réponse ici.",
   "lle_copiar": "📋 Copier la question et le texte",
   "lle_copiado": "✓ Copié — collez-le dans claude.ai",
   "lle_abrir": "↗ Ouvrir claude.ai",
   "tra_expl": "Collez ici ce que claude.ai a rendu. C'est un objet JSON : il commence par { et finit par }.",
   "tra_pegar": "Collez la réponse ici",
   "tra_guardar": "✓ Ranger dans le dossier",
   "tra_leido": "Lu",
   "tra_mal": "Ça ne ressemble pas à du JSON. Copiez la réponse entière, sans le texte autour.",
   "dia_vacio": "Le journal est vide.",
   "sin_exp": "⚠ aucun dossier ouvert"
  },
  "ca": {
   "tit_doc": "📄 El document",
   "tit_llevar": "📋 Portar-ho a claude.ai",
   "tit_traer": "📥 Portar la resposta",
   "tit_diario": "📓 El diari",
   "doc_suelte": "Deixi aquí un PDF, o toqui per triar-lo",
   "doc_o_pegue": "…o enganxi el text directament",
   "doc_pegar": "Enganxi el text aquí",
   "doc_ocr": "🔍 Reconèixer el text (OCR)",
   "doc_ocr_curso": "⏳ Reconeixent…",
   "doc_ocr_hecho": "✓ Text reconegut",
   "doc_sin_servidor": "L'OCR necessita el servidor. Arrenqui Salufolio amb la seva abella 🐝.",
   "lle_expl": "Copiï tot i enganxi'ho a claude.ai. Després porti la resposta aquí.",
   "lle_copiar": "📋 Copiar",
   "lle_copiado": "✓ Copiat",
   "lle_abrir": "↗ Obrir claude.ai",
   "tra_expl": "Enganxi aquí el que claude.ai ha tornat.",
   "tra_pegar": "Enganxi la resposta",
   "tra_guardar": "✓ Guardar a l'expedient",
   "tra_leido": "Llegit",
   "tra_mal": "Això no sembla JSON.",
   "dia_vacio": "El diari està buit.",
   "sin_exp": "⚠ cap expedient obert"
  },
  "en": {
   "tit_doc": "📄 The document",
   "tit_llevar": "📋 Take it to claude.ai",
   "tit_traer": "📥 Bring the answer back",
   "tit_diario": "📓 The log",
   "doc_suelte": "Drop a PDF here, or tap to pick one",
   "doc_o_pegue": "…or paste the text directly, if you have it",
   "doc_pegar": "Paste the text here",
   "doc_ocr": "🔍 Recognise the text (OCR)",
   "doc_ocr_curso": "⏳ Recognising…",
   "doc_ocr_hecho": "✓ Text recognised",
   "doc_sin_servidor": "OCR needs the server. Start Salufolio with its bee 🐝 and come back.",
   "lle_expl": "Copy it all —the question and the text— and paste it into a claude.ai conversation. Then bring the answer back here.",
   "lle_copiar": "📋 Copy the question and the text",
   "lle_copiado": "✓ Copied — paste it into claude.ai",
   "lle_abrir": "↗ Open claude.ai",
   "tra_expl": "Paste here what claude.ai returned. It's a JSON object: starts with { and ends with }.",
   "tra_pegar": "Paste the answer here",
   "tra_guardar": "✓ Save to the record",
   "tra_leido": "Read",
   "tra_mal": "That doesn't look like JSON. Copy the whole answer, without the surrounding text.",
   "dia_vacio": "The log is empty.",
   "sin_exp": "⚠ no record open"
  }
 }
};
