var CELLS=[
  /* Rangée 0 */
  {id:'proto',icon:'📱',label:'Protocolo',sub:'el día a día',color:'#4a8fe8',content:'<h3>La aplicación del móvil</h3><div id="proto-puente"></div><p>Tomas, medidas y notas del día, junto a la cama. Funciona <strong>sin conexión y sin PC</strong> — cuando el ordenador se enciende, los datos suben solos por el Pont WiFi.</p><p>✔ Tomas · 📊 Constantes · ✎ Corrección de días pasados · 📦 Material</p><p><a id="proto-abrir" href="protocolo/index.html" style="color:var(--accent);font-weight:700;font-size:16px">→ Abrir Protocolo</a></p>'},
  {id:'express',icon:'⚡',label:'Informe express',sub:'Para el médico',color:'#4ae86a',action:function(){irSalufolio('Salufolio.html?tour=0&express=1')}},   /* l'écran du toubib en UN geste (P-H 19/07) — l'Extractor a déménagé au Taller */
  /* Rangée 1 */
  {id:'auditoria',icon:'🔍',label:'Auditoría',sub:'coherencia clínica',color:'#e84a4a',content:'<h3>El juez de paz del expediente</h3><p>Señala lo que no cuadra: <strong>diagnósticos sin soporte analítico</strong>, valores imposibles, identificadores en colisión, antecedentes fósiles, material listado como fármaco.</p><p>✔ Conforme · ✏️ Corregir · 📄 Ver el documento</p><p><strong>La auditoría señala; el juicio es humano.</strong></p>'},
  {id:'home',icon:'🩺',label:'Salufolio',sub:'Acceder',color:'#2a9d5f',action:function(){irSalufolio('Salufolio.html?tour=0')}},   /* accès direct — la visite ne s'impose plus (P-H 17/07) */
  {id:'farmaco',icon:'💊',label:'Farmacovigilancia',sub:'en construcción',color:'#8a4ae8',obra:true,content:'<h3>En el taller 🚧</h3><p>Principio activo y código ATC vía la <strong>API pública CIMA/AEMPS</strong>: marca ↔ genérico, duplicidades de principio activo, interacciones.</p><p>El material (oxígeno, absorbentes) queda fuera: no son medicamentos.</p>'},
  /* Rangée 2 */
  {id:'ensayo',icon:'🧪',label:'Ensayo clínico',sub:'GCP · ICH E6',color:'#4ac8e8',obra:true,content:'<h3>Salufolio para la investigación</h3><p>Visitas, eventos adversos, reportador y sello de tiempo: el módulo que abre el expediente a <strong>los ensayos clínicos</strong> — el uso que más piden los profesionales.</p>'},
  {id:'builder',icon:'🧱',label:'ModularBuilder',sub:'el taller',color:'#d4c44a',content:'<h3>Donde se fabrica todo</h3><p><strong>79 módulos</strong> ensamblados en un archivo único: build, split, punto fijo, empaquetado.</p><p>Herramienta universal — no depende de Salufolio; Salufolio depende de ella.</p><p>📥 <strong>Extractor</strong> — del papel al dato: lee los PDF y los convierte en valores fechados con su fuente; las extracciones se guardan (♻️ el mismo documento nunca se paga dos veces). <em>Salufolio no inventa nada.</em></p>'}
];


/* ═══ LE REZ-DE-CHAUSSÉE (perfiles) — déménagé d'index.html le 29/08,
   doctrine P-H : les données hors du code, comme les textes. ═══ */
var SUB=[
  {icon:'🧑',label:'Paciente',sub:'Su historial',color:'#4ae8a4',action:function(){irSalufolio('Salufolio.html?tour=0&perfil=paciente')}},
  {icon:'👨‍⚕️',label:'Profesional',sub:'Vista completa',color:'#e8e84a',action:function(){irSalufolio('Salufolio.html?tour=0&perfil=medico')}},
  {icon:'👨‍👩‍👧',label:'Cuidador',sub:'Protocolo',color:'#e84a8a',action:function(){irA('protocolo/index.html')}},
  {icon:'🩺',label:'Salufolio',sub:'Acceder',color:'#2a9d5f',action:function(){irSalufolio('Salufolio.html?tour=0')}},   /* P-H 19/07 : le stéthoscope ENTRE toujours — dans les deux essaims */
  {icon:'🎓',label:'Visita guiada',sub:'el panal, puerta a puerta',color:'#4ae8e8',action:function(){arrancarVisita()}},
  {icon:'📊',label:'Saber más',sub:'En números',color:'#e8a44a',content:'<div class="sr"><div class="si"><span class="sn">10</span><span class="slab">Años</span></div><div class="si"><span class="sn">79</span><span class="slab">Módulos</span></div><div class="si"><span class="sn">510</span><span class="slab">Valores</span></div><div class="si"><span class="sn">36</span><span class="slab">Documentos</span></div></div><h3>¿Qué significan estos números?</h3><p>Son los números de la <strong>demostración en línea</strong>: un caso real de <strong>diez años</strong> de historia clínica, cuidadosamente anonimizado. Diez años que antes vivían dispersos — un documento aquí, un informe allá — y hoy conviven en un solo lugar, ordenados por fecha. <strong>510 valores</strong> de análisis y constantes que antes había que buscar uno a uno; ahora se comparan de un vistazo — año tras año, mes tras mes, día tras día. <strong>36 documentos</strong> ya leídos y clasificados por Salufolio, cada uno con su fecha y su origen siempre a mano.</p><h3>¿Qué es Salufolio?</h3><p>Un expediente médico longitudinal: <strong>un único archivo</strong>, sin conexión a internet, sin servidor, sin nube. Sus datos no salen nunca de su aparato.</p><p><strong>Es libre y gratuito</strong>: nadie puede vendérselo ni cerrarlo — su licencia (GNU GPL v3) garantiza que siempre será de todos. Y está <strong>registrado y archivado para siempre</strong> en Zenodo, el archivo científico europeo (DOI 10.5281/zenodo.21997587) — como se registra una publicación.</p>'},
  {icon:'📧',label:'Contacto',sub:'MediFolio@proton.me',color:'#8a4ae8',content:'PFB'}
];
