/* Los textos del informe */
var SF_TEXTOS = window.SF_TEXTOS = {
 "_doctrina": "Los textos del informe. Nada escrito en el código.",
 "textos": {
  "es": {
   "titulo_express": "Informe express",
   "para": "para la consulta",
   "elegir": "¿Qué informe hace falta?",
   "elegir_sub": "Los tres salen del mismo expediente. Cambia a quién se le da.",
   "anon": "Anonimizar antes de darlo",
   "anon_que": "Los datos clínicos no se tocan: son ellos lo que se quiere mostrar. Sólo se quita de quién son.",
   "anon_nivel": "Hasta dónde:",
   "anon_hecho": "Datos anonimizados",
   "volver": "← Volver a elegir",
   "imprimir": "🖨 Imprimir",
   "menos": "A−",
   "mas": "A+",
   "zoom": "Tamaño de la letra",
   "sec_situacion": "Situación actual",
   "situacion_sub": "observaciones del cuidador",
   "situ_vacia": "Toque aquí y escriba lo observado en casa (fatiga, saturación, ejercicios, tomas…). Se guarda solo y reaparece la próxima vez.",
   "sec_tratamiento": "Tratamiento actual",
   "tratamiento_sub": "con fechas",
   "material": "Material",
   "sec_eventos": "Eventos recientes",
   "sec_fuera": "Valores fuera de rango",
   "ultimos": "últimos {n} días",
   "col_param": "Parámetro",
   "col_fecha": "Fecha",
   "col_anterior": "Anterior",
   "col_valor": "Valor",
   "col_ref": "Ref.",
   "sec_vigilar": "A vigilar",
   "vigilar_sub": "presentamos los dos parámetros que más se mueven ({n} días)",
   "historico": "histórico completo",
   "fuentes": "Fuentes",
   "vigilar_dice": "La pendiente habla: valor a vigilar en la próxima analítica.",
   "fuera_rango": "FUERA DE RANGO",
   "en_dias": "en {n} días",
   "pie_express": "Salufolio — expediente longitudinal local del paciente. Cada dato procede de informes oficiales importados o del registro del cuidador. Salufolio no inventa nada.",
   "paciente": "Paciente",
   "generado": "Generado",
   "periodo": "Período",
   "datos": "Datos",
   "autor": "Autor",
   "fechas": "fechas",
   "eventos": "eventos",
   "sec_anamnesis": "Anamnesis y síntesis clínica",
   "anamnesis": "Expediente con {f} fechas de análisis, {e} eventos clínicos y {m} medicamentos documentados en los últimos {meses} meses.",
   "sec_fuera_lista": "Valores fuera de rango ({n})",
   "sec_medicacion": "Medicación documentada",
   "meses_ult": "últimos {n} meses",
   "col_fechadoc": "Fecha doc.",
   "col_medicamento": "Medicamento",
   "col_dosis": "Dosis",
   "col_frecuencia": "Frecuencia",
   "col_estado": "Estado*",
   "col_prescriptor": "Prescriptor / Fuente",
   "nota_estado": "* Estado según el documento de origen (fecha indicada) — la medicación realmente activa puede diferir 47 entradas más antiguas en el expediente Salufolio.",
   "sec_fichas": "Últimos valores conocidos",
   "sec_tabla": "Tabla de síntesis cronológica",
   "col_fuente": "Fuente",
   "sec_curvas": "Curvas de evolución",
   "curvas_sub": "parámetros significativos",
   "sec_modulos": "Módulos",
   "seccion": "Sección",
   "de": "de",
   "nada_curvas": "No hay bastantes puntos para dibujar una curva.",
   "nada_fuera": "Nada fuera de rango en este período.",
   "nada_periodo": "No hay nada en este período.",
   "sin_exp": "Ningún expediente abierto.",
   "cmt_titulo": "Comentario de las curvas",
   "cmt_generar": "Pedir un comentario",
   "cmt_regenerar": "Pedirlo de nuevo",
   "cmt_pensando": "Leyendo las curvas…",
   "cmt_firma": "Comentario generado por Claude (Anthropic) el {fecha} — no sustituye el juicio clínico.",
   "cmt_sin_clave": "Hace falta una clave de la API. Se pone en la adquisición automática.",
   "cmt_sin_curvas": "No hay curvas en pantalla que comentar.",
   "cmt_sin_cambios": "El comentario del {fecha} se hizo con estos mismos datos. ¿Pedirlo otra vez? Consumirá una llamada.",
   "cmt_error": "No ha salido bien: {error}",
   "copiar": "📋 Copiar",
   "copiado": "✓ Copiado",
   "guardar": "Guardar",
   "guardado": "Guardado",
   "clave_titulo": "La clave de la API",
   "clave_que": "Para pedirle a Claude un comentario de las curvas hace falta una clave de la API de Anthropic. Se guarda en este navegador y no sale de él.",
   "clave_campo": "Clave",
   "clave_donde": "Se pone una sola vez: vale también para la adquisición automática.",
   "clave_corta": "Eso no parece una clave. Empieza por sk-ant-",
   "cancelar": "Cancelar",
   "cmt_falta_clave": "Hace falta una clave API para ver una valoración clínica de la IA.",
   "cmt_pedir_clave": "Pedir una clave",
   "clave_ok": "OK",
   "clave_obtener": "Obtener clave API",
   "clave_sin": "Sin clave API",
   "clave_como": "Para conseguir una clave:\n\n1 · Abra console.anthropic.com y cree una cuenta si no la tiene.\n2 · Vaya a Settings → API keys.\n3 · Toque «Create Key» y copie lo que sale.\n4 · Péguelo en el campo de Salufolio.\n\nLa clave se guarda en este navegador y no sale de él. Cada llamada cuesta unos céntimos.\n\nSi prefiere no pagar, use «Sin clave API»: se lleva el texto a claude.ai y se trae la respuesta a mano.",
   "cmt_copiado_prompt": "Copiado. Péguelo en claude.ai y traiga la respuesta.",
   "cmt_pega_aqui": "Pegue aquí lo que Claude ha contestado:",
   "otros_fuera": "Otros {n} valores están fuera de rango y no figuran aquí:",
   "hay_detallado": "Un informe más detallado está disponible — está a su disposición.",
   "sin_fin": "sin fecha de fin",
   "y_otros": "y otros {n} más — tóquelo para verlos",
   "otros": "Otros",
   "principios": "principios",
   "documentos": "documentos",
   "nota_plegada": "▸ Un medicamento recetado en varios documentos se pliega: se ven la última y la primera. Toque el ▸ para las demás.",
   "sec_antecedentes": "Antecedentes",
   "todo": "todo",
   "ant_activos": "Activos",
   "ant_inactivos": "Resueltos",
   "cmt_anular": "Anular",
   "cmt_anular_que": "Corta la espera. Pero la llamada ya en curso puede contarse igualmente: la API ha empezado a trabajar.",
   "cmt_anulado": "Espera anulada. La llamada ya en curso puede haberse contado.",
   "col_anyos": "Años",
   "col_antecedente": "Antecedente",
   "col_capitulo": "Capítulo",
   "distintos": "distintos",
   "mas_llenos": "los más presentes",
   "demo_corto": "Demostración — caso real anonimizado, 14 años"
  },
  "fr": {
   "titulo_express": "Rapport express",
   "para": "pour la consultation",
   "elegir": "Quel rapport faut-il ?",
   "elegir_sub": "Les trois sortent du même dossier. Ce qui change, c'est à qui on le donne.",
   "anon": "Anonymiser avant de le donner",
   "anon_que": "Les données cliniques ne sont pas touchées : c'est elles qu'on veut montrer. On retire seulement de qui elles sont.",
   "anon_nivel": "Jusqu'où :",
   "anon_hecho": "Données anonymisées",
   "volver": "← Revenir au choix",
   "imprimir": "🖨 Imprimer",
   "menos": "A−",
   "mas": "A+",
   "zoom": "Taille des lettres",
   "sec_situacion": "Situation actuelle",
   "situacion_sub": "ce que l'aidant observe",
   "situ_vacia": "Touchez ici et écrivez ce que vous observez à la maison (fatigue, saturation, exercices, prises…). Ça se garde tout seul et reparaît la prochaine fois.",
   "sec_tratamiento": "Traitement actuel",
   "tratamiento_sub": "avec les dates",
   "material": "Matériel",
   "sec_eventos": "Événements récents",
   "sec_fuera": "Valeurs hors des bornes",
   "ultimos": "{n} derniers jours",
   "col_param": "Paramètre",
   "col_fecha": "Date",
   "col_anterior": "Précédent",
   "col_valor": "Valeur",
   "col_ref": "Réf.",
   "sec_vigilar": "À surveiller",
   "vigilar_sub": "nous présentons les deux paramètres qui bougent le plus ({n} jours)",
   "historico": "tout l'historique",
   "fuentes": "Sources",
   "vigilar_dice": "La pente parle : valeur à surveiller à la prochaine analyse.",
   "fuera_rango": "HORS DES BORNES",
   "en_dias": "en {n} jours",
   "pie_express": "Salufolio — dossier longitudinal local du patient. Chaque donnée vient d'un rapport officiel importé ou de ce qu'a noté l'aidant. Salufolio n'invente rien.",
   "paciente": "Patient",
   "generado": "Fait le",
   "periodo": "Période",
   "datos": "Données",
   "autor": "Auteur",
   "fechas": "dates",
   "eventos": "événements",
   "sec_anamnesis": "Anamnèse et synthèse clinique",
   "anamnesis": "Dossier de {f} dates d'analyse, {e} événements cliniques et {m} médicaments documentés sur les {meses} derniers mois.",
   "sec_fuera_lista": "Valeurs hors des bornes ({n})",
   "sec_medicacion": "Médication documentée",
   "meses_ult": "{n} derniers mois",
   "col_fechadoc": "Date doc.",
   "col_medicamento": "Médicament",
   "col_dosis": "Dose",
   "col_frecuencia": "Posologie",
   "col_estado": "État*",
   "col_prescriptor": "Prescripteur / Source",
   "nota_estado": "* État selon le document d'origine (date indiquée) — la médication réellement en cours peut différer.",
   "sec_fichas": "Derniers résultats connus",
   "sec_tabla": "Table de synthèse chronologique",
   "col_fuente": "Source",
   "sec_curvas": "Courbes d'évolution",
   "curvas_sub": "paramètres significatifs",
   "sec_modulos": "Modules",
   "seccion": "Section",
   "de": "sur",
   "nada_curvas": "Pas assez de points pour tracer une courbe.",
   "nada_fuera": "Rien hors des bornes sur cette période.",
   "nada_periodo": "Il n'y a rien sur cette période.",
   "sin_exp": "Aucun dossier ouvert.",
   "cmt_titulo": "Commentaire des courbes",
   "cmt_generar": "Demander un commentaire",
   "cmt_regenerar": "Le redemander",
   "cmt_pensando": "Lecture des courbes…",
   "cmt_firma": "Commentaire écrit par Claude (Anthropic) le {fecha} — il ne remplace pas le jugement clinique.",
   "cmt_sin_clave": "Il faut une clé de l'API. Elle se pose dans l'acquisition automatique.",
   "cmt_sin_curvas": "Aucune courbe à l'écran à commenter.",
   "cmt_sin_cambios": "Le commentaire du {fecha} a été fait avec ces mêmes données. Le redemander ? Cela coûtera un appel.",
   "cmt_error": "Ça n'a pas marché : {error}",
   "copiar": "📋 Copier",
   "copiado": "✓ Copié",
   "guardar": "Garder",
   "guardado": "Gardé",
   "clave_titulo": "La clé de l'API",
   "clave_que": "Pour demander à Claude un commentaire des courbes, il faut une clé de l'API d'Anthropic. Elle se garde dans ce navigateur et n'en sort pas.",
   "clave_campo": "Clé",
   "clave_donde": "On la pose une seule fois : elle vaut aussi pour l'acquisition automatique.",
   "clave_corta": "Ça ne ressemble pas à une clé. Elle commence par sk-ant-",
   "cancelar": "Annuler",
   "cmt_falta_clave": "Il faut une clé API pour voir une appréciation clinique de l'IA.",
   "cmt_pedir_clave": "Demander une clé",
   "clave_ok": "OK",
   "clave_obtener": "Obtenir une clé API",
   "clave_sin": "Sans clé API",
   "clave_como": "Pour obtenir une clé :\n\n1 · Ouvrez console.anthropic.com et créez un compte si vous n'en avez pas.\n2 · Allez dans Settings → API keys.\n3 · Touchez «Create Key» et copiez ce qui sort.\n4 · Collez-le dans le champ de Salufolio.\n\nLa clé se garde dans ce navigateur et n'en sort pas. Chaque appel coûte quelques centimes.\n\nSi vous préférez ne pas payer, employez «Sans clé API» : on porte le texte à claude.ai et on rapporte la réponse à la main.",
   "cmt_copiado_prompt": "Copié. Collez-le dans claude.ai et rapportez la réponse.",
   "cmt_pega_aqui": "Collez ici ce que Claude a répondu :",
   "otros_fuera": "{n} autres valeurs sont hors des bornes et ne figurent pas ici :",
   "hay_detallado": "Un rapport plus détaillé existe — il est à votre disposition.",
   "sin_fin": "sans date de fin",
   "y_otros": "et {n} autres — touchez pour les voir",
   "otros": "Autres",
   "principios": "principes",
   "documentos": "documents",
   "nota_plegada": "▸ Un médicament prescrit dans plusieurs documents se replie : on voit la dernière et la première. Touchez le ▸ pour les autres.",
   "sec_antecedentes": "Antécédents",
   "todo": "tout",
   "ant_activos": "Actifs",
   "ant_inactivos": "Résolus",
   "cmt_anular": "Annuler",
   "cmt_anular_que": "Coupe l'attente. Mais l'appel déjà en cours peut être compté quand même : l'API a commencé à travailler.",
   "cmt_anulado": "Attente annulée. L'appel déjà en cours a peut-être été compté.",
   "col_anyos": "Années",
   "col_antecedente": "Antécédent",
   "col_capitulo": "Chapitre",
   "distintos": "distincts",
   "mas_llenos": "les plus présents",
   "demo_corto": "Démonstration — cas réel anonymisé, 14 ans"
  },
  "ca": {
   "titulo_express": "Informe express",
   "para": "per a la consulta",
   "elegir": "Quin informe cal?",
   "elegir_sub": "Els tres ixen del mateix expedient.",
   "anon": "Anonimitzar abans de donar-lo",
   "anon_que": "Les dades clíniques no es toquen.",
   "anon_nivel": "Fins on:",
   "anon_hecho": "Dades anonimitzades",
   "volver": "← Tornar a triar",
   "imprimir": "🖨 Imprimir",
   "menos": "A−",
   "mas": "A+",
   "zoom": "Grandària de la lletra",
   "sec_situacion": "Situació actual",
   "situacion_sub": "observacions del cuidador",
   "situ_vacia": "Toque ací i escriga el que observa a casa.",
   "sec_tratamiento": "Tractament actual",
   "tratamiento_sub": "amb dates",
   "material": "Material",
   "sec_eventos": "Esdeveniments recents",
   "sec_fuera": "Valors fora de rang",
   "ultimos": "últims {n} dies",
   "col_param": "Paràmetre",
   "col_fecha": "Data",
   "col_anterior": "Anterior",
   "col_valor": "Valor",
   "col_ref": "Ref.",
   "sec_vigilar": "A vigilar",
   "vigilar_sub": "presentem els dos paràmetres que més es mouen ({n} dies)",
   "historico": "històric complet",
   "fuentes": "Fonts",
   "vigilar_dice": "El pendent parla: valor a vigilar en la pròxima analítica.",
   "fuera_rango": "FORA DE RANG",
   "en_dias": "en {n} dies",
   "pie_express": "Salufolio — expedient longitudinal local del pacient. Salufolio no s'inventa res.",
   "paciente": "Pacient",
   "generado": "Generat",
   "periodo": "Període",
   "datos": "Dades",
   "autor": "Autor",
   "fechas": "dates",
   "eventos": "esdeveniments",
   "sec_anamnesis": "Anamnesi i síntesi clínica",
   "anamnesis": "Expedient amb {f} dates d'anàlisi, {e} esdeveniments i {m} medicaments en els últims {meses} mesos.",
   "sec_fuera_lista": "Valors fora de rang ({n})",
   "sec_medicacion": "Medicació documentada",
   "meses_ult": "últims {n} mesos",
   "col_fechadoc": "Data doc.",
   "col_medicamento": "Medicament",
   "col_dosis": "Dosi",
   "col_frecuencia": "Freqüència",
   "col_estado": "Estat*",
   "col_prescriptor": "Prescriptor / Font",
   "nota_estado": "* Estat segons el document d'origen.",
   "sec_fichas": "Últims valors coneguts",
   "sec_tabla": "Taula de síntesi cronològica",
   "col_fuente": "Font",
   "sec_curvas": "Corbes d'evolució",
   "curvas_sub": "paràmetres significatius",
   "sec_modulos": "Mòduls",
   "seccion": "Secció",
   "de": "de",
   "nada_curvas": "No hi ha prou punts.",
   "nada_fuera": "Res fora de rang.",
   "nada_periodo": "No hi ha res en este període.",
   "sin_exp": "Cap expedient obert.",
   "cmt_titulo": "Comentari de les corbes",
   "cmt_generar": "Demanar un comentari",
   "cmt_regenerar": "Demanar-lo de nou",
   "cmt_pensando": "Llegint les corbes…",
   "cmt_firma": "Comentari generat per Claude (Anthropic) el {fecha}.",
   "cmt_sin_clave": "Cal una clau de l'API.",
   "cmt_sin_curvas": "No hi ha corbes.",
   "cmt_sin_cambios": "El comentari del {fecha} es va fer amb estes dades.",
   "cmt_error": "No ha eixit bé: {error}",
   "copiar": "📋 Copiar",
   "copiado": "✓ Copiat",
   "guardar": "Guardar",
   "guardado": "Guardat",
   "clave_titulo": "La clau de l'API",
   "clave_que": "Per demanar-li a Claude un comentari de les corbes cal una clau de l'API d'Anthropic. Es guarda en este navegador.",
   "clave_campo": "Clau",
   "clave_donde": "Es posa una sola vegada: val també per a l'adquisició automàtica.",
   "clave_corta": "Això no sembla una clau.",
   "cancelar": "Cancel·lar",
   "cmt_falta_clave": "Cal una clau API per veure una valoració clínica de la IA.",
   "cmt_pedir_clave": "Demanar una clau",
   "clave_ok": "OK",
   "clave_obtener": "Obtindre clau API",
   "clave_sin": "Sense clau API",
   "clave_como": "Per aconseguir una clau:\n\n1 · Òbriga console.anthropic.com.\n2 · Vaja a Settings → API keys.\n3 · Toque «Create Key» i copie el que ix.\n4 · Apegue-ho al camp de Salufolio.\n\nLa clau es guarda en este navegador.",
   "cmt_copiado_prompt": "Copiat. Apegue-ho a claude.ai.",
   "cmt_pega_aqui": "Apegue ací el que Claude ha contestat:",
   "otros_fuera": "Altres {n} valors estan fora de rang i no figuren ací:",
   "hay_detallado": "Un informe més detallat està a la seua disposició.",
   "sin_fin": "sense data de fi",
   "y_otros": "i {n} més — toque per veure'ls",
   "otros": "Altres",
   "principios": "principis",
   "documentos": "documents",
   "nota_plegada": "▸ Un medicament receptat en diversos documents es plega: es veuen l'última i la primera.",
   "sec_antecedentes": "Antecedents",
   "todo": "tot",
   "ant_activos": "Actius",
   "ant_inactivos": "Resolts",
   "cmt_anular": "Anul·lar",
   "cmt_anular_que": "Talla l'espera. Però la crida ja en curs pot comptar-se igualment.",
   "cmt_anulado": "Espera anul·lada. La crida ja en curs pot haver-se comptat.",
   "col_anyos": "Anys",
   "col_antecedente": "Antecedent",
   "col_capitulo": "Capítol",
   "distintos": "distints",
   "mas_llenos": "els més presents",
   "demo_corto": "Demostració — cas real anonimitzat, 14 anys"
  },
  "en": {
   "titulo_express": "Express report",
   "para": "for the visit",
   "elegir": "Which report is needed?",
   "elegir_sub": "All three come from the same record. What changes is who gets it.",
   "anon": "Anonymise before handing it over",
   "anon_que": "The clinical data are untouched: they are what you want to show.",
   "anon_nivel": "How far:",
   "anon_hecho": "Data anonymised",
   "volver": "← Back to the choice",
   "imprimir": "🖨 Print",
   "menos": "A−",
   "mas": "A+",
   "zoom": "Text size",
   "sec_situacion": "Current situation",
   "situacion_sub": "what the carer sees",
   "situ_vacia": "Tap here and write what you see at home (tiredness, saturation, exercises, doses…). It saves itself and comes back next time.",
   "sec_tratamiento": "Current treatment",
   "tratamiento_sub": "with dates",
   "material": "Equipment",
   "sec_eventos": "Recent events",
   "sec_fuera": "Values out of range",
   "ultimos": "last {n} days",
   "col_param": "Parameter",
   "col_fecha": "Date",
   "col_anterior": "Previous",
   "col_valor": "Value",
   "col_ref": "Ref.",
   "sec_vigilar": "To watch",
   "vigilar_sub": "here are the two parameters moving most ({n} days)",
   "historico": "full history",
   "fuentes": "Sources",
   "vigilar_dice": "The slope speaks: watch this at the next lab.",
   "fuera_rango": "OUT OF RANGE",
   "en_dias": "in {n} days",
   "pie_express": "Salufolio — the patient's own longitudinal record. Every figure comes from an imported official report or from what the carer noted. Salufolio invents nothing.",
   "paciente": "Patient",
   "generado": "Made on",
   "periodo": "Period",
   "datos": "Data",
   "autor": "Author",
   "fechas": "dates",
   "eventos": "events",
   "sec_anamnesis": "History and clinical summary",
   "anamnesis": "Record with {f} lab dates, {e} clinical events and {m} medications documented over the last {meses} months.",
   "sec_fuera_lista": "Values out of range ({n})",
   "sec_medicacion": "Documented medication",
   "meses_ult": "last {n} months",
   "col_fechadoc": "Doc. date",
   "col_medicamento": "Medication",
   "col_dosis": "Dose",
   "col_frecuencia": "Schedule",
   "col_estado": "Status*",
   "col_prescriptor": "Prescriber / Source",
   "nota_estado": "* Status per the source document — what is actually being taken may differ.",
   "sec_fichas": "Latest known values",
   "sec_tabla": "Chronological summary table",
   "col_fuente": "Source",
   "sec_curvas": "Evolution curves",
   "curvas_sub": "significant parameters",
   "sec_modulos": "Modules",
   "seccion": "Section",
   "de": "of",
   "nada_curvas": "Not enough points to draw a curve.",
   "nada_fuera": "Nothing out of range in this period.",
   "nada_periodo": "Nothing in this period.",
   "sin_exp": "No record open.",
   "cmt_titulo": "Comment on the curves",
   "cmt_generar": "Ask for a comment",
   "cmt_regenerar": "Ask again",
   "cmt_pensando": "Reading the curves…",
   "cmt_firma": "Comment written by Claude (Anthropic) on {fecha} — it does not replace clinical judgement.",
   "cmt_sin_clave": "An API key is needed.",
   "cmt_sin_curvas": "No curves to comment on.",
   "cmt_sin_cambios": "The comment of {fecha} was made with these same data. Ask again?",
   "cmt_error": "That didn't work: {error}",
   "copiar": "📋 Copy",
   "copiado": "✓ Copied",
   "guardar": "Save",
   "guardado": "Saved",
   "clave_titulo": "The API key",
   "clave_que": "To ask Claude for a comment on the curves you need an Anthropic API key. It is kept in this browser and never leaves it.",
   "clave_campo": "Key",
   "clave_donde": "Set it once: it also works for automatic acquisition.",
   "clave_corta": "That doesn't look like a key. It starts with sk-ant-",
   "cancelar": "Cancel",
   "cmt_falta_clave": "An API key is needed to see a clinical appraisal from the AI.",
   "cmt_pedir_clave": "Ask for a key",
   "clave_ok": "OK",
   "clave_obtener": "Get an API key",
   "clave_sin": "Without a key",
   "clave_como": "To get a key:\n\n1 · Open console.anthropic.com and create an account if you don't have one.\n2 · Go to Settings → API keys.\n3 · Tap «Create Key» and copy what comes out.\n4 · Paste it into Salufolio's field.\n\nThe key stays in this browser. Each call costs a few cents.\n\nIf you'd rather not pay, use «Without a key»: you take the text to claude.ai and bring the answer back by hand.",
   "cmt_copiado_prompt": "Copied. Paste it into claude.ai and bring the answer back.",
   "cmt_pega_aqui": "Paste here what Claude answered:",
   "otros_fuera": "{n} further values are out of range and are not shown here:",
   "hay_detallado": "A fuller report exists — it is at your disposal.",
   "sin_fin": "no end date",
   "y_otros": "and {n} more — tap to see them",
   "otros": "Other",
   "principios": "substances",
   "documentos": "documents",
   "nota_plegada": "▸ A medication prescribed in several documents is folded: the latest and the earliest are shown. Tap the ▸ for the rest.",
   "sec_antecedentes": "Medical history",
   "todo": "all",
   "ant_activos": "Active",
   "ant_inactivos": "Resolved",
   "cmt_anular": "Cancel",
   "cmt_anular_que": "Stops the waiting. But the call already under way may be charged anyway: the API has started work.",
   "cmt_anulado": "Waiting cancelled. The call already under way may have been charged.",
   "col_anyos": "Years",
   "col_antecedente": "Condition",
   "col_capitulo": "Chapter",
   "distintos": "distinct",
   "mas_llenos": "most present",
   "demo_corto": "Demonstration — real case, anonymised, 14 years"
  }
 }
};
