/* Los textos de la adquisición manual */
var SF_TEXTOS = window.SF_TEXTOS = {
 "_doctrina": "Los textos. Las rúbricas tienen los suyos en la tabla.",
 "textos": {
  "es": {
   "tit_visto": "✍️ Lo escrito a mano",
   "tit_diario": "📓 El diario",
   "intro": "Escoja qué quiere escribir. El formulario se dibuja solo, con sus límites y sus unidades — todo viene de la tabla.",
   "guardar": "Guardar el expediente",
   "guardado": "Guardado",
   "guardado_linea": "✓ Añadido",
   "vacio": "Todavía no ha escrito nada. Empiece por donde quiera.",
   "solo_otros": "Nada escrito a mano todavía. Hay {n} línea(s) que vienen de otro sitio — para verlas, use Revisar.",
   "ya_en_exp": "ya en el expediente",
   "dia_vacio": "El diario está vacío.",
   "en_sesion": "En esta sesión",
   "sin_exp": "⚠ ningún expediente abierto",
   "nada_guardar": "No hay nada que guardar.",
   "u_mediciones": "mediciones",
   "u_eventos": "eventos",
   "u_medicamentos": "medicamentos",
   "conf_texto": "Se va a guardar en el expediente de {quien}, con lo que acaba de escribir. Lo que había antes no se toca.",
   "no_guardar": "No guardar",
   "si_guardar": "Sí, guardar",
   "cancelar": "Cancelar",
   "id_titulo": "¿De quién es este expediente?",
   "id_texto": "Lo que ha escrito todavía no pertenece a nadie. Diga de quién es, y se creará su expediente.",
   "id_nombre": "Nombre y apellidos",
   "id_nac": "Nacimiento",
   "id_mat": "Matrícula",
   "id_falta": "Hacen falta el nombre y el SIP.",
   "id_existe": "Ya existe un expediente con la matrícula {mat}. Se guardará ahí, junto a lo que ya hay.",
   "crear_guardar": "Crear y guardar"
  },
  "fr": {
   "tit_visto": "✍️ Ce qui est écrit à la main",
   "tit_diario": "📓 Le journal",
   "intro": "Choisissez ce que vous voulez écrire. Le formulaire se dessine tout seul, avec ses bornes et ses unités — tout vient de la table.",
   "guardar": "Garder le dossier",
   "guardado": "Gardé",
   "guardado_linea": "✓ Ajouté",
   "vacio": "Vous n'avez encore rien écrit. Commencez où vous voulez.",
   "solo_otros": "Rien d'écrit à la main pour l'instant. Il y a {n} ligne(s) venues d'ailleurs — pour les voir, employez Revisar.",
   "ya_en_exp": "déjà dans le dossier",
   "dia_vacio": "Le journal est vide.",
   "en_sesion": "Dans cette séance",
   "sin_exp": "⚠ aucun dossier ouvert",
   "nada_guardar": "Il n'y a rien à garder.",
   "u_mediciones": "mesures",
   "u_eventos": "événements",
   "u_medicamentos": "médicaments",
   "conf_texto": "On va garder dans le dossier de {quien}, avec ce que vous venez d'écrire. Ce qu'il y avait avant n'est pas touché.",
   "no_guardar": "Ne pas garder",
   "si_guardar": "Oui, garder",
   "cancelar": "Annuler",
   "id_titulo": "À qui est ce dossier ?",
   "id_texto": "Ce que vous avez écrit n'appartient encore à personne. Dites de qui il s'agit, et son dossier sera créé.",
   "id_nombre": "Nom et prénoms",
   "id_nac": "Naissance",
   "id_mat": "Matricule",
   "id_falta": "Il faut le nom et le SIP.",
   "id_existe": "Un dossier existe déjà avec la matricule {mat}. On y gardera, à côté de ce qui s'y trouve.",
   "crear_guardar": "Créer et garder"
  },
  "ca": {
   "tit_visto": "✍️ El que s'ha escrit a mà",
   "tit_diario": "📓 El diari",
   "intro": "Triï què vol escriure. El formulari es dibuixa sol.",
   "guardar": "Guardar l'expedient",
   "guardado": "Guardat",
   "guardado_linea": "✓ Afegit",
   "vacio": "Encara no ha escrit res.",
   "solo_otros": "Res escrit a mà encara. Hi ha {n} línia(es) d'altres llocs.",
   "ya_en_exp": "ja a l'expedient",
   "dia_vacio": "El diari està buit.",
   "en_sesion": "En aquesta sessió",
   "sin_exp": "⚠ cap expedient obert",
   "nada_guardar": "No hi ha res per guardar.",
   "u_mediciones": "mesures",
   "u_eventos": "esdeveniments",
   "u_medicamentos": "medicaments",
   "conf_texto": "Es guardarà a l'expedient de {quien}.",
   "no_guardar": "No guardar",
   "si_guardar": "Sí, guardar",
   "cancelar": "Cancel·lar",
   "id_titulo": "De qui és aquest expedient?",
   "id_texto": "Digui de qui és.",
   "id_nombre": "Nom i cognoms",
   "id_nac": "Naixement",
   "id_mat": "Matrícula",
   "id_falta": "Calen el nom i el SIP.",
   "id_existe": "Ja existeix la matrícula {mat}.",
   "crear_guardar": "Crear i guardar"
  },
  "en": {
   "tit_visto": "✍️ Written by hand",
   "tit_diario": "📓 The log",
   "intro": "Pick what you want to write. The form draws itself, with its limits and units — it all comes from the table.",
   "guardar": "Save the record",
   "guardado": "Saved",
   "guardado_linea": "✓ Added",
   "vacio": "Nothing written yet. Start wherever you like.",
   "solo_otros": "Nothing written by hand yet. There are {n} line(s) from elsewhere — use Revisar to see them.",
   "ya_en_exp": "already in the record",
   "dia_vacio": "The log is empty.",
   "en_sesion": "This session",
   "sin_exp": "⚠ no record open",
   "nada_guardar": "Nothing to save.",
   "u_mediciones": "measurements",
   "u_eventos": "events",
   "u_medicamentos": "medications",
   "conf_texto": "This will be saved to {quien}'s record, with what you've just written.",
   "no_guardar": "Don't save",
   "si_guardar": "Yes, save",
   "cancelar": "Cancel",
   "id_titulo": "Whose record is this?",
   "id_texto": "What you've written belongs to no one yet. Say whose it is.",
   "id_nombre": "Name",
   "id_nac": "Born",
   "id_mat": "ID",
   "id_falta": "Name and SIP are needed.",
   "id_existe": "A record already exists with ID {mat}.",
   "crear_guardar": "Create and save"
  }
 }
};
