/* Los textos de la adquisición manual */
var SF_TEXTOS = window.SF_TEXTOS = {
 "_doctrina": "Los textos. Las rúbricas tienen los suyos en la tabla.",
 "textos": {
  "es": {
   "tit_visto": "✍️ Lo escrito a mano",
   "tit_diario": "📓 El diario",
   "intro": "Escoja qué quiere escribir. El formulario se dibuja solo, con sus límites y sus unidades.",
   "guardar": "Guardar el expediente",
   "guardado": "Guardado",
   "guardado_linea": "✓ Añadido",
   "vacio": "Todavía no ha escrito nada. Empiece por donde quiera.",
   "solo_otros": "Nada escrito a mano todavía. Hay {n} línea(s) que vienen de otro sitio — para verlas, use Revisar.",
   "ya_en_exp": "ya en el expediente",
   "dia_vacio": "El diario está vacío.",
   "en_sesion": "En esta sesión",
   "sin_exp": "⚠ ningún expediente abierto",
   "nada_guardar": "No hay nada que guardar.",
   "u_mediciones": "mediciones",
   "u_eventos": "eventos",
   "u_medicamentos": "medicamentos",
   "conf_texto": "Se va a guardar en el expediente de {quien}, con lo que acaba de escribir. Lo que había antes no se toca.",
   "no_guardar": "No guardar",
   "si_guardar": "Sí, guardar",
   "cancelar": "Cancelar",
   "id_titulo": "¿De quién es este expediente?",
   "id_texto": "Lo que ha escrito todavía no pertenece a nadie. Diga de quién es, y se creará su expediente.",
   "id_nombre": "Nombre y apellidos",
   "id_nac": "Nacimiento",
   "id_mat": "Matrícula",
   "id_falta": "Hacen falta el nombre y el SIP.",
   "id_existe": "Ya existe un expediente con la matrícula {mat}. Se guardará ahí, junto a lo que ya hay.",
   "crear_guardar": "Crear y guardar",
   "tip_guardar": "Escribe todo lo anotado en el expediente del paciente, en un fichero nuevo. Lo de antes no se toca.",
   "donde_va": "Dónde va a parar",
   "donde_nota": "Con el servidor arrancado, la carpeta se crea sola si no existe. Sin servidor, el navegador descargará el fichero y tendrá que colocarlo usted en esa carpeta.",
   "expl_visto": "Todo lo que ha escrito a mano en esta sesión y en las anteriores. Toque una línea para corregirla, la ✕ para quitarla.",
   "expl_diario": "Una línea por sesión de trabajo: cuándo, y cuántas cosas se añadieron. No es un dato médico — es el cuaderno del trabajo."
  },
  "fr": {
   "tit_visto": "✍️ Ce qui est écrit à la main",
   "tit_diario": "📓 Le journal",
   "intro": "Choisissez ce que vous voulez écrire. Le formulaire se dessine tout seul, avec ses bornes et ses unités.",
   "guardar": "Garder le dossier",
   "guardado": "Gardé",
   "guardado_linea": "✓ Ajouté",
   "vacio": "Vous n'avez encore rien écrit. Commencez où vous voulez.",
   "solo_otros": "Rien d'écrit à la main pour l'instant. Il y a {n} ligne(s) venues d'ailleurs — pour les voir, employez Revisar.",
   "ya_en_exp": "déjà dans le dossier",
   "dia_vacio": "Le journal est vide.",
   "en_sesion": "Dans cette séance",
   "sin_exp": "⚠ aucun dossier ouvert",
   "nada_guardar": "Il n'y a rien à garder.",
   "u_mediciones": "mesures",
   "u_eventos": "événements",
   "u_medicamentos": "médicaments",
   "conf_texto": "On va garder dans le dossier de {quien}, avec ce que vous venez d'écrire. Ce qu'il y avait avant n'est pas touché.",
   "no_guardar": "Ne pas garder",
   "si_guardar": "Oui, garder",
   "cancelar": "Annuler",
   "id_titulo": "À qui est ce dossier ?",
   "id_texto": "Ce que vous avez écrit n'appartient encore à personne. Dites de qui il s'agit, et son dossier sera créé.",
   "id_nombre": "Nom et prénoms",
   "id_nac": "Naissance",
   "id_mat": "Matricule",
   "id_falta": "Il faut le nom et le SIP.",
   "id_existe": "Un dossier existe déjà avec la matricule {mat}. On y gardera, à côté de ce qui s'y trouve.",
   "crear_guardar": "Créer et garder",
   "tip_guardar": "Écrit tout ce qui a été noté dans le dossier du patient, en un fichier neuf. Ce qu'il y avait avant n'est pas touché.",
   "donde_va": "Où le fichier va atterrir",
   "donde_nota": "Avec le serveur lancé, le dossier se crée tout seul s'il n'existe pas. Sans serveur, le navigateur téléchargera le fichier et il faudra le poser vous-même dans ce dossier.",
   "expl_visto": "Tout ce que vous avez écrit à la main, dans cette séance et les précédentes. Touchez une ligne pour la corriger, la ✕ pour la retirer.",
   "expl_diario": "Une ligne par séance de travail : quand, et combien de choses ont été ajoutées. Ce n'est pas une donnée médicale — c'est le cahier du travail."
  },
  "ca": {
   "tit_visto": "✍️ El que s'ha escrit a mà",
   "tit_diario": "📓 El diari",
   "intro": "Triï què vol escriure. El formulari es dibuixa sol, amb els seus límits i les seves unitats.",
   "guardar": "Guardar l'expedient",
   "guardado": "Guardat",
   "guardado_linea": "✓ Afegit",
   "vacio": "Encara no ha escrit res.",
   "solo_otros": "Res escrit a mà encara. Hi ha {n} línia(es) d'altres llocs.",
   "ya_en_exp": "ja a l'expedient",
   "dia_vacio": "El diari està buit.",
   "en_sesion": "En aquesta sessió",
   "sin_exp": "⚠ cap expedient obert",
   "nada_guardar": "No hi ha res per guardar.",
   "u_mediciones": "mesures",
   "u_eventos": "esdeveniments",
   "u_medicamentos": "medicaments",
   "conf_texto": "Es guardarà a l'expedient de {quien}.",
   "no_guardar": "No guardar",
   "si_guardar": "Sí, guardar",
   "cancelar": "Cancel·lar",
   "id_titulo": "De qui és aquest expedient?",
   "id_texto": "Digui de qui és.",
   "id_nombre": "Nom i cognoms",
   "id_nac": "Naixement",
   "id_mat": "Matrícula",
   "id_falta": "Calen el nom i el SIP.",
   "id_existe": "Ja existeix la matrícula {mat}.",
   "crear_guardar": "Crear i guardar",
   "tip_guardar": "Escriu tot el que s'ha anotat a l'expedient, en un fitxer nou.",
   "donde_va": "On anirà a parar",
   "donde_nota": "Amb el servidor arrencat, la carpeta es crea sola. Sense servidor, haurà de col·locar el fitxer vostè.",
   "expl_visto": "Tot el que ha escrit a mà. Toqui una línia per corregir-la, la ✕ per treure-la.",
   "expl_diario": "Una línia per sessió: quan, i quantes coses s'han afegit."
  },
  "en": {
   "tit_visto": "✍️ Written by hand",
   "tit_diario": "📓 The log",
   "intro": "Pick what you want to write. The form draws itself, with its limits and units.",
   "guardar": "Save the record",
   "guardado": "Saved",
   "guardado_linea": "✓ Added",
   "vacio": "Nothing written yet. Start wherever you like.",
   "solo_otros": "Nothing written by hand yet. There are {n} line(s) from elsewhere — use Revisar to see them.",
   "ya_en_exp": "already in the record",
   "dia_vacio": "The log is empty.",
   "en_sesion": "This session",
   "sin_exp": "⚠ no record open",
   "nada_guardar": "Nothing to save.",
   "u_mediciones": "measurements",
   "u_eventos": "events",
   "u_medicamentos": "medications",
   "conf_texto": "This will be saved to {quien}'s record, with what you've just written.",
   "no_guardar": "Don't save",
   "si_guardar": "Yes, save",
   "cancelar": "Cancel",
   "id_titulo": "Whose record is this?",
   "id_texto": "What you've written belongs to no one yet. Say whose it is.",
   "id_nombre": "Name",
   "id_nac": "Born",
   "id_mat": "ID",
   "id_falta": "Name and SIP are needed.",
   "id_existe": "A record already exists with ID {mat}.",
   "crear_guardar": "Create and save",
   "tip_guardar": "Writes everything noted into the patient's record, as a new file. What was there before is untouched.",
   "donde_va": "Where it will land",
   "donde_nota": "With the server running, the folder is created for you. Without it, the browser downloads the file and you must place it there yourself.",
   "expl_visto": "Everything written by hand, this session and before. Tap a line to correct it, the ✕ to remove it.",
   "expl_diario": "One line per working session: when, and how much was added. Not medical data — it's the work notebook."
  }
 }
};
