/* ══════════════════════════════════════════════════════════════════════
   LOS TEXTOS de la adquisición automática

   Nada en duro: cada texto lleva su clave. P-H la llama « la tabla de
   las lenguas » — la otra palabra, la de los anglófonos con prisa, la
   detesta.
   ══════════════════════════════════════════════════════════════════════ */
var SF_TEXTOS = window.SF_TEXTOS = {
 "_doctrina": "Los textos del programa. Nada en duro en el HTML: cada uno lleva su\nclave, y la tabla dice cómo se escribe en cada lengua.\n\nP-H odia la palabra « i18n » —jerga de anglófono con prisa. Aquí se llama\nlo que es: la tabla de las lenguas.",
 "textos": {
  "es": {
   "tit_config": "⚙️ Configuración de la extracción",
   "tit_leer": "📄 Leer documentos",
   "tit_diario": "📓 El diario",
   "cfg_intro": "Este programa pide a Claude que lea sus documentos. No es gratuito, pero cuesta poco: unos céntimos por informe. Hace falta una cuenta en {consola}, y allí se crea la clave — un texto largo que empieza por {sk}.",
   "cfg_gratis": "Si prefiere no pagar nada, el modo {asistida} hace lo mismo: se copia el texto en claude.ai y se trae la respuesta a mano.",
   "cfg_clave": "🔑 Clave API",
   "cfg_quien": "🤖 Quién lee",
   "cfg_que": "📄 Qué se le pide",
   "cfg_cuanto": "🔢 Cuánto puede devolver",
   "cfg_cuanto_expl": "<b>Cuánto puede devolver</b> es el tamaño máximo de la respuesta. « Informes de alta » equivale a unas cuarenta páginas de texto, y va bien para casi todo.<br>Si un documento se corta a medias, el diario lo dirá con todas las letras y bastará con elegir el escalón siguiente.",
   "cfg_guardar": "Guardar la configuración",
   "cfg_ok": "✓ La clave está guardada en este aparato.",
   "cfg_sin": "Sin clave, este programa no puede leer nada. El modo {asistida} no la necesita.",
   "tok_cortos": "Informes cortos",
   "tok_habitual": "Lo habitual",
   "tok_alta": "Informes de alta — recomendado",
   "tok_largos": "Documentos muy largos",
   "mod_rapido": "Sonnet — rápido y barato",
   "mod_fino": "Opus — más fino, más caro",
   "leer_suelte": "Suelte aquí los PDF, o toque para elegirlos",
   "leer_uno": "Se leen uno tras otro. Cada uno deja su línea en el diario.",
   "leer_detener": "⏹ Detener",
   "leer_parando": "⏹ Parando…",
   "leer_leyendo": "Leyendo",
   "leer_detenido": "Detenido",
   "leer_sin_clave": "Hace falta una clave API para leer documentos.",
   "leer_sin_exp": "Abra primero un expediente con 📂 — si no, lo leído no se ata a nadie.",
   "leer_sin_prompt": "Para leer un documento hace falta el prompt, y sin servidor el navegador no puede abrir el fichero donde vive.<br><br>Arranque Salufolio con su abeja 🐝 —o escriba <code>salufolio</code>— y vuelva aquí. O use el modo {asistida}, que no necesita nada de eso.",
   "dia_intro": "Cada documento leído deja aquí su línea: cuándo, qué fichero, qué se sacó, y las dudas que Claude haya devuelto. Vive en el expediente del paciente.",
   "dia_vacio": "El diario está vacío. Cada documento leído dejará aquí su línea.",
   "dia_guardar": "💾 Guardar lo leído",
   "dia_diario": "📓 Guardar el diario",
   "dia_repe": "ya leído",
   "dia_repe_expl": "el mismo documento que {otro} — la GVA lo da otra vez con otra hora de impresión. No se ha vuelto a guardar.",
   "det_fichero": "fichero",
   "det_cuando": "cuándo",
   "det_sesion": "sesión",
   "det_modo": "modo",
   "det_duracion": "duración",
   "det_quien": "quién leyó",
   "det_que": "qué se pidió",
   "det_fuente": "fuente",
   "det_sacado": "sacado",
   "det_error": "error",
   "det_segundos": "segundos",
   "det_cerrar": "Cerrar",
   "det_desplegar": "— tocar para desplegar",
   "dia_limpiar": "🧹 Limpiar el diario",
   "dia_limpiar_expl": "El diario guarda una línea por documento leído. Con los años se alarga.",
   "dia_limpiar_hay": "Aquí hay {n} línea(s), desde el {desde}.",
   "dia_quitar_antes": "Quitar lo anterior a:",
   "dia_quitar_todo": "Quitarlo todo",
   "dia_cancelar": "Cancelar",
   "dia_quitar": "Quitar",
   "mod_A": "automática",
   "mod_M": "manual",
   "mod_S": "asistida"
  },
  "fr": {
   "tit_config": "⚙️ Configuration de l'extraction",
   "tit_leer": "📄 Lire des documents",
   "tit_diario": "📓 Le journal",
   "cfg_intro": "Ce programme demande à Claude de lire vos documents. Ce n'est pas gratuit, mais ça coûte peu : quelques centimes par rapport. Il faut un compte sur {consola}, où l'on crée la clé — un long texte qui commence par {sk}.",
   "cfg_gratis": "Si vous préférez ne rien payer, le mode {asistida} fait la même chose : on copie le texte dans claude.ai et on rapporte la réponse à la main.",
   "cfg_clave": "🔑 Clé API",
   "cfg_quien": "🤖 Qui lit",
   "cfg_que": "📄 Ce qu'on lui demande",
   "cfg_cuanto": "🔢 Combien il peut rendre",
   "cfg_cuanto_expl": "<b>Combien il peut rendre</b> est la taille maximale de la réponse. « Comptes rendus de sortie » vaut une quarantaine de pages, et convient à presque tout.<br>Si un document est coupé en chemin, le journal le dira en toutes lettres et il suffira de choisir le cran suivant.",
   "cfg_guardar": "Garder la configuration",
   "cfg_ok": "✓ La clé est gardée dans cet appareil.",
   "cfg_sin": "Sans clé, ce programme ne peut rien lire. Le mode {asistida} n'en a pas besoin.",
   "tok_cortos": "Rapports courts",
   "tok_habitual": "L'ordinaire",
   "tok_alta": "Comptes rendus de sortie — recommandé",
   "tok_largos": "Documents très longs",
   "mod_rapido": "Sonnet — rapide et peu cher",
   "mod_fino": "Opus — plus fin, plus cher",
   "leer_suelte": "Déposez les PDF ici, ou touchez pour les choisir",
   "leer_uno": "Ils sont lus l'un après l'autre. Chacun laisse sa ligne au journal.",
   "leer_detener": "⏹ Arrêter",
   "leer_parando": "⏹ On s'arrête…",
   "leer_leyendo": "Lecture de",
   "leer_detenido": "Arrêté",
   "leer_sin_clave": "Il faut une clé API pour lire des documents.",
   "leer_sin_exp": "Ouvrez d'abord un dossier avec 📂 — sinon ce qui est lu ne s'attache à personne.",
   "leer_sin_prompt": "Pour lire un document il faut le prompt, et sans serveur le navigateur ne peut pas ouvrir le fichier où il vit.<br><br>Lancez Salufolio par son abeille 🐝 —ou tapez <code>salufolio</code>— et revenez ici. Ou employez le mode {asistida}, qui n'a besoin de rien de tout ça.",
   "dia_intro": "Chaque document lu laisse ici sa ligne : quand, quel fichier, ce qui en est sorti, et les doutes que Claude a rendus. Il vit dans le dossier du patient.",
   "dia_vacio": "Le journal est vide. Chaque document lu y laissera sa ligne.",
   "dia_guardar": "💾 Garder ce qui est lu",
   "dia_diario": "📓 Garder le journal",
   "dia_repe": "déjà lu",
   "dia_repe_expl": "le même document que {otro} — la GVA le redonne avec une autre heure d'impression. Rien n'a été rangé.",
   "det_fichero": "fichier",
   "det_cuando": "quand",
   "det_sesion": "séance",
   "det_modo": "mode",
   "det_duracion": "durée",
   "det_quien": "qui a lu",
   "det_que": "ce qu'on a demandé",
   "det_fuente": "source",
   "det_sacado": "ce qui est sorti",
   "det_error": "erreur",
   "det_segundos": "secondes",
   "det_cerrar": "Fermer",
   "det_desplegar": "— toucher pour déplier",
   "dia_limpiar": "🧹 Nettoyer le journal",
   "dia_limpiar_expl": "Le journal garde une ligne par document lu. Avec les années il s'allonge.",
   "dia_limpiar_hay": "Il y a ici {n} ligne(s), depuis le {desde}.",
   "dia_quitar_antes": "Retirer ce qui est avant :",
   "dia_quitar_todo": "Tout retirer",
   "dia_cancelar": "Annuler",
   "dia_quitar": "Retirer",
   "mod_A": "automatique",
   "mod_M": "manuel",
   "mod_S": "assistée"
  },
  "ca": {
   "tit_config": "⚙️ Configuració de l'extracció",
   "tit_leer": "📄 Llegir documents",
   "tit_diario": "📓 El diari",
   "cfg_intro": "Aquest programa demana a Claude que llegeixi els seus documents. No és gratuït, però costa poc: uns cèntims per informe. Cal un compte a {consola}, i allà es crea la clau — un text llarg que comença per {sk}.",
   "cfg_gratis": "Si prefereix no pagar res, el mode {asistida} fa el mateix: es copia el text a claude.ai i es porta la resposta a mà.",
   "cfg_clave": "🔑 Clau API",
   "cfg_quien": "🤖 Qui llegeix",
   "cfg_que": "📄 Què se li demana",
   "cfg_cuanto": "🔢 Quant pot tornar",
   "cfg_cuanto_expl": "<b>Quant pot tornar</b> és la mida màxima de la resposta. « Informes d'alta » equival a unes quaranta pàgines de text.<br>Si un document es talla a mitges, el diari ho dirà i n'hi haurà prou amb triar l'esglaó següent.",
   "cfg_guardar": "Guardar la configuració",
   "cfg_ok": "✓ La clau està guardada en aquest aparell.",
   "cfg_sin": "Sense clau, aquest programa no pot llegir res. El mode {asistida} no la necessita.",
   "tok_cortos": "Informes curts",
   "tok_habitual": "L'habitual",
   "tok_alta": "Informes d'alta — recomanat",
   "tok_largos": "Documents molt llargs",
   "mod_rapido": "Sonnet — ràpid i barat",
   "mod_fino": "Opus — més fi, més car",
   "leer_suelte": "Deixi aquí els PDF, o toqui per triar-los",
   "leer_uno": "Es llegeixen l'un rere l'altre. Cadascun deixa la seva línia al diari.",
   "leer_detener": "⏹ Aturar",
   "leer_parando": "⏹ Aturant…",
   "leer_leyendo": "Llegint",
   "leer_detenido": "Aturat",
   "leer_sin_clave": "Cal una clau API per llegir documents.",
   "leer_sin_exp": "Obri primer un expedient amb 📂 — si no, el que es llegeix no s'ata a ningú.",
   "leer_sin_prompt": "Per llegir un document cal el prompt, i sense servidor el navegador no pot obrir el fitxer on viu.<br><br>Arrenqui Salufolio amb la seva abella 🐝 i torni aquí. O faci servir el mode {asistida}.",
   "dia_intro": "Cada document llegit deixa aquí la seva línia. Viu a l'expedient del pacient.",
   "dia_vacio": "El diari està buit.",
   "dia_guardar": "💾 Guardar el llegit",
   "dia_diario": "📓 Guardar el diari",
   "dia_repe": "ja llegit",
   "dia_repe_expl": "el mateix document que {otro}.",
   "det_fichero": "fitxer",
   "det_cuando": "quan",
   "det_sesion": "sessió",
   "det_modo": "mode",
   "det_duracion": "durada",
   "det_quien": "qui ha llegit",
   "det_que": "què s'ha demanat",
   "det_fuente": "font",
   "det_sacado": "el que ha sortit",
   "det_error": "error",
   "det_segundos": "segons",
   "det_cerrar": "Tancar",
   "det_desplegar": "— tocar per desplegar",
   "dia_limpiar": "🧹 Netejar el diari",
   "dia_limpiar_expl": "El diari guarda una línia per document llegit.",
   "dia_limpiar_hay": "Aquí hi ha {n} línia(es), des del {desde}.",
   "dia_quitar_antes": "Treure el que és anterior a:",
   "dia_quitar_todo": "Treure-ho tot",
   "dia_cancelar": "Cancel·lar",
   "dia_quitar": "Treure",
   "mod_A": "automàtica",
   "mod_M": "manual",
   "mod_S": "assistida"
  },
  "en": {
   "tit_config": "⚙️ Extraction settings",
   "tit_leer": "📄 Read documents",
   "tit_diario": "📓 The log",
   "cfg_intro": "This program asks Claude to read your documents. Not free, but cheap: a few cents per report. You need an account at {consola}, where the key is created — a long text starting with {sk}.",
   "cfg_gratis": "If you'd rather pay nothing, the {asistida} mode does the same: paste the text into claude.ai and bring the answer back by hand.",
   "cfg_clave": "🔑 API key",
   "cfg_quien": "🤖 Who reads",
   "cfg_que": "📄 What it's asked",
   "cfg_cuanto": "🔢 How much it can return",
   "cfg_cuanto_expl": "<b>How much it can return</b> is the maximum answer size. « Discharge reports » is about forty pages of text, and suits almost everything.<br>If a document gets cut short, the log will say so plainly and you need only pick the next step up.",
   "cfg_guardar": "Save the settings",
   "cfg_ok": "✓ The key is saved on this device.",
   "cfg_sin": "Without a key this program can read nothing. The {asistida} mode doesn't need one.",
   "tok_cortos": "Short reports",
   "tok_habitual": "The usual",
   "tok_alta": "Discharge reports — recommended",
   "tok_largos": "Very long documents",
   "mod_rapido": "Sonnet — fast and cheap",
   "mod_fino": "Opus — finer, dearer",
   "leer_suelte": "Drop the PDFs here, or tap to pick them",
   "leer_uno": "They're read one after another. Each leaves its line in the log.",
   "leer_detener": "⏹ Stop",
   "leer_parando": "⏹ Stopping…",
   "leer_leyendo": "Reading",
   "leer_detenido": "Stopped",
   "leer_sin_clave": "An API key is needed to read documents.",
   "leer_sin_exp": "Open a record first with 📂 — otherwise what's read belongs to nobody.",
   "leer_sin_prompt": "Reading a document needs the prompt, and without a server the browser cannot open the file it lives in.<br><br>Start Salufolio with its bee 🐝 —or type <code>salufolio</code>— and come back. Or use the {asistida} mode, which needs none of that.",
   "dia_intro": "Every document read leaves its line here. It lives in the patient's record.",
   "dia_vacio": "The log is empty.",
   "dia_guardar": "💾 Save what was read",
   "dia_diario": "📓 Save the log",
   "dia_repe": "already read",
   "dia_repe_expl": "the same document as {otro}.",
   "det_fichero": "file",
   "det_cuando": "when",
   "det_sesion": "session",
   "det_modo": "mode",
   "det_duracion": "duration",
   "det_quien": "who read",
   "det_que": "what was asked",
   "det_fuente": "source",
   "det_sacado": "what came out",
   "det_error": "error",
   "det_segundos": "seconds",
   "det_cerrar": "Close",
   "det_desplegar": "— tap to unfold",
   "dia_limpiar": "🧹 Clean up the log",
   "dia_limpiar_expl": "The log keeps a line per document read. Over the years it grows.",
   "dia_limpiar_hay": "There are {n} line(s) here, since {desde}.",
   "dia_quitar_antes": "Remove anything before:",
   "dia_quitar_todo": "Remove it all",
   "dia_cancelar": "Cancel",
   "dia_quitar": "Remove",
   "mod_A": "automatic",
   "mod_M": "manual",
   "mod_S": "assisted"
  }
 }
};
